version: "3.8"

# $ docker compose up -d

services:
  startpage:
    container_name: startpage
    build: ../../start
    restart: 'unless-stopped'
    ports:
      - "8080:80"
    networks:
      - "traefik_proxy"
    labels:
      # Enable traefik
      - 'traefik.enable=true'
      - "traefik.port=80"
      - 'traefik.http.routers.glances.rule=Host(`startpage.saber.sidequest.space`)'
      - 'traefik.http.routers.glances.entryPoints=websecure'
      - 'traefik.http.routers.glances.tls=true'
      - 'traefik.http.routers.glances.tls.certResolver=myresolver'

networks:
  traefik_proxy:
    external: true
