version: "3.9"
services:
  glances:
    image: nicolargo/glances:3.4.0.3-full
    container_name: glances
    restart: 'unless-stopped'
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    labels:
      # Enable traefik
      - 'traefik.enable=true'
      - "traefik.port=61208"
      - 'traefik.http.routers.glances.rule=Host(`glances.saber.sidequest.space`)'
      - 'traefik.http.routers.glances.entryPoints=web'
