version: "3.9"
services:
  glances:
    image: nicolargo/glances:3.4.0.3-full
    container_name: glances
    privileged: true
    restart: 'unless-stopped'
    environment:
      - GLANCES_OPT=-C /glances/conf/glances.conf -w
      - TZ=Asia/Kolkata
    networks:
      - "traefik_proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # mount root to allow disk stats
      - /:/rootfs:ro
      # show host os stats
      - /etc/os-release:/etc/os-release:ro
      - /home/amish/applications/saber/glances/glances.conf:/glances/conf/glances.conf:ro
    pid: host
    labels:
      # Enable traefik
      - 'traefik.enable=true'
      - "traefik.port=61208"
      - 'traefik.http.routers.glances.rule=Host(`glances.saber.sidequest.space`)'
      - 'traefik.http.routers.glances.entryPoints=websecure'
      - 'traefik.http.routers.glances.tls=true'
      - 'traefik.http.routers.glances.tls.certResolver=myresolver'

networks:
  traefik_proxy:
    external: true
