[log]
  level = "DEBUG"

[providers]
  [providers.docker]
    exposedByDefault = false

[api]
  dashboard = true

[certificatesResolvers.myresolver.acme]
  storage = "/traefik/acme.json"
  [certificatesResolvers.myresolver.acme.dnschallenge]
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
    provider = "cloudflare"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
