[log]
  level = "DEBUG"

[providers]
  [providers.docker]
    exposedByDefault = false

[api]
  dashboard = true

[certificatesResolvers.myresolver.acme]
  storage = "/traefik/acme.json"
  [certificatesResolvers.myresolver.acme.dnschallenge]
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
    # HACK: can't get the usual workflow to work
    # lego can't check the dns record on CF's authority server
    delaybeforecheck = 60
    disablepropagationcheck = true

    provider = "cloudflare"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
