version: "3.9"

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN
    volumes:
      - /home/amish/db/cloudflared:/etc/cloudflared
    networks:
      - "tunnel"

networks:
  tunnel:
