version: '3.9'

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: 'unless-stopped'
    # user: "1000:1000"
    volumes:
      - /media/data/media:/srv
      - /home/amish/db/filebrowser:/database
    networks:
      - "traefik_proxy"
    labels:
      # Enable traefik
      - 'traefik.enable=true'
      - "traefik.port=80"
      - 'traefik.http.services.filebrowser.loadbalancer.server.port=80'
      - 'traefik.http.routers.filebrowser.rule=Host(`filebrowser.saber.sidequest.space`)'
      - 'traefik.http.routers.filebrowser.entryPoints=websecure'
      - 'traefik.http.routers.filebrowser.tls=true'
      - 'traefik.http.routers.filebrowser.tls.certResolver=myresolver'


networks:
  traefik_proxy:
    external: true
