version: "3.9"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    user: 1000:1000
    volumes:
      - /home/amish/db/jellyfin:/config
      - /home/amish/applications/saber/jellyfin/config.json:/config/config.json:ro
      - /media/data/cache/jellyfin:/cache
      - /media/data/media:/media:ro
    restart: 'unless-stopped'
    # override what the server sends out as it's autodiscover address
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.saber.sidequest.space
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      # Enable traefik
      - 'traefik.enable=true'
      # Router
      - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.saber.sidequest.space`)'
      - 'traefik.http.routers.jellyfin.entryPoints=web'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'
