version: "3.9"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - /home/amish/db/jellyfin:/config
      - /home/amish/applications/saber/jellyfin/config.json:/config/config.json:ro
      - /media/data/cache/jellyfin:/cache
      - /media/data/media:/media
    networks:
      - "traefik_proxy"
    restart: 'unless-stopped'
    # override what the server sends out as it's autodiscover address
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.saber.sidequest.space
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
    labels:
      # Enable traefik
      - 'traefik.enable=true'
      # Router
      - "traefik.port=8096"
      - 'traefik.http.routers.jellyfinhttp.rule=Host(`jellyfin.saber.sidequest.space`)'
      - 'traefik.http.routers.jellyfinhttp.entryPoints=web'
      - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.saber.sidequest.space`)'
      - 'traefik.http.routers.jellyfin.entryPoints=websecure'
      - 'traefik.http.routers.jellyfin.tls=true'
      - 'traefik.http.routers.jellyfin.tls.certResolver=myresolver'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'

networks:
  traefik_proxy:
    external: true
